### PR TITLE
Rewrite message parsing to be cleaner

### PR DESCRIPTION
**Pull request by belak**
This is a port of the message parsing from my old `.Trailing` pull request, written to work the same as the current parsing.

### CODE REVIEW

**Comment by belak** [comment]
Note that there is one change. The only param which can be empty is the Trailing arg. The tests were updated to account for this.

**Comment by sorcix** [comment]
Ran the benchmarks while on the train.

Looks like this code doubles the time spent parsing a longer message. I will check this out a little better if I have time this evening. Might be because my code ignored unicode, your code should be a lot more stable if people use special characters.

Pull request:
```
go test -bench .                                                                                                                                                                                                             8:56:53
PASS
BenchmarkPrefix_String_short-4  2000000000               1.98 ns/op            0 B/op          0 allocs/op
BenchmarkPrefix_String_long-4   20000000               105 ns/op               0 B/op          0 allocs/op
BenchmarkParsePrefix_short-4    20000000               107 ns/op              48 B/op          1 allocs/op
BenchmarkParsePrefix_long-4     20000000                89.1 ns/op            48 B/op          1 allocs/op
BenchmarkMessage_String-4        5000000               258 ns/op             176 B/op          2 allocs/op
BenchmarkParseMessage_short-4    2000000               627 ns/op             144 B/op          3 allocs/op
BenchmarkParseMessage_medium-4   2000000               962 ns/op             240 B/op          5 allocs/op
BenchmarkParseMessage_long-4     1000000              1485 ns/op             320 B/op          5 allocs/op
```

Current master:
```
$ go test -bench .                                                                                                                                                                                                   8:58:49
PASS
BenchmarkPrefix_String_short-4  2000000000               1.98 ns/op            0 B/op          0 allocs/op
BenchmarkPrefix_String_long-4   20000000               104 ns/op               0 B/op          0 allocs/op
BenchmarkParsePrefix_short-4    20000000               106 ns/op              48 B/op          1 allocs/op
BenchmarkParsePrefix_long-4     20000000                88.6 ns/op            48 B/op          1 allocs/op
BenchmarkMessage_String-4        5000000               261 ns/op             176 B/op          2 allocs/op
BenchmarkParseMessage_short-4    5000000               294 ns/op              96 B/op          2 allocs/op
BenchmarkParseMessage_medium-4   3000000               514 ns/op             160 B/op          3 allocs/op
BenchmarkParseMessage_long-4     2000000               669 ns/op             240 B/op          3 allocs/op
```

**Comment by belak** [comment]
I'm sure there'd be a way to improve the performance of this without giving up the cleaner parsing. I'll experiment if I get the chance.

**Comment by belak** [comment]
I've been considering this and I think if we use strings.Index but use the same methods I've been using here, it'll be closer to the same speed.

I'd be willing to bet that there are a lot of extra slice operations.

**Comment by belak** [comment]
I'm dropping this for now, as I don't think this provides enough of a benefit over what is currently supported.

**Pull request closed without merging**
