### PR TITLE
Properly handle colons in non-trailing params

### PR DESCRIPTION
**Pull request by belak**
This fixes the issue I brought up in #18 (but not the actual issue mentioned, as I couldn't reproduce it)

### CODE REVIEW

**Comment by belak** [comment]
Note that this doesn't fix the master branch, but this should probably be backported.

**Comment by sorcix** [comment]
Thanks! I'll check out this change and backport it next weekend.

**Comment by belak** [comment]
Is there any feedback for this?

**Comment by sorcix** [comment]
Thanks, rebased on v2 and merged.

**Pull request closed without merging**
